# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from concurrent.futures import Future
from license_manager import LicenseManager
from mlx_audio.tts.generate import load_audio
from mlx_audio.tts.utils import load_model
from typing import Any
import datetime
import gradio
import json
import mlx.core
import numpy
import os
import queue
import re
import shutil
import soundfile
import threading
import time

MODEL_ROOT = '/Users/macpro/chatterbox'
DEFAULT_LANG_CODE = 'tr'
OUTPUT_PATH = 'uretilen_ses.wav'
YOUTUBE_MASTER_PATH = 'uretilen_ses_youtube_master.wav'
SUPPORTED_LANGUAGES = {'tr': 'Turkish / Türkçe', 'en': 'English', 'ar': 'Arabic', 'da': 'Danish', 'de': 'German', 'el': 'Greek', 'es': 'Spanish', 'fi': 'Finnish', 'fr': 'French', 'he': 'Hebrew', 'hi': 'Hindi', 'it': 'Italian', 'ja': 'Japanese', 'ko': 'Korean', 'ms': 'Malay', 'nl': 'Dutch', 'no': 'Norwegian', 'pl': 'Polish', 'pt': 'Portuguese', 'ru': 'Russian', 'sv': 'Swedish', 'sw': 'Swahili', 'zh': 'Chinese'}
CHUNKS_DIR = 'generated_chunks'
PRESETS_FILE = 'voice_presets.json'
PRESETS_AUDIO_DIR = 'saved_voice_refs'
PAUSE_MS = {'short': 300, 'medium': 650, 'long': 1000}
LANGUAGE_TTS_PROFILES = {'tr': {'preview_name': 'Türkçe standart profil'}, 'ar': {'preview_name': 'Arabic narrative slower reference profile', 'max_cfg_with_ref': 0.28, 'max_cfg_without_ref': 0.34, 'max_exaggeration_with_ref': 0.38, 'max_exaggeration_without_ref': 0.46, 'max_temperature_with_ref': 0.26, 'max_temperature_without_ref': 0.34, 'max_chunk_size_with_ref': 150, 'max_chunk_size_without_ref': 165, 'min_chunk_gap_with_ref_ms': 120, 'min_chunk_gap_without_ref_ms': 90, 'auto_token_mul': 1.38, 'auto_token_bias': 120, 'auto_token_min': 220, 'auto_token_max': 640, 'duration_divisor': 9.0, 'duration_bias': 6.5, 'duration_floor': 8.5}}
ARABIC_STORY_STRONG_MARKERS = ['في تلك الليله', 'في تلك الليلة', 'في ذلك المساء', 'في تلك اللحظه', 'في تلك اللحظة', 'في ذلك الوقت', 'في احد الايام', 'في احدى العشيات', 'في احدى الغدوات', 'في احدى الامسيات', 'في صباح', 'وفي صباح', 'بعد ايام قليله', 'بعد ايام', 'بعد ذلك', 'مرت الايام', 'مضت الاسابيع', 'تحولت الاسابيع', 'في الايام التاليه', 'في الأيام التالية', 'جاء يوم', 'وصلت فاطمه', 'عادت فاطمه', 'زارتها العجوز', 'اما في', 'وفي بيت', 'وفي ذلك المساء', 'وفي احد الايام', 'وعند اول فرصه', 'مع قدوم الخريف', 'حين اطل', 'مضت السنوات']
ARABIC_STORY_SOFT_MARKERS = {'لكن', 'ثم', 'بينما', 'وعندما', 'وحين', 'وبعد', 'بعد', 'وفي', 'اما', 'فجاه', 'دخل', 'خرج', 'نظر', 'نظرت', 'قال', 'قالت', 'تمتمت', 'اجابت', 'وقفت', 'رفعت', 'شعرت', 'جاء', 'عادت', 'وصلت'}
ARABIC_COMMON_PHRASE_FIXES = [('مرحبا بكم احبائي المستمعين في عالم القصص الراقيه وخير ما نبدا به الصلاه والسلام على سيدنا وحبيبنا محمد صلى الله عليه وسلم', 'مرحباً بكم، أحبائي المستمعين، في عالم القصص الراقية.\nوخير ما نبدأ به الصلاة والسلام على سيدنا وحبيبنا محمد، صلى الله عليه وسلم.'), ('مرحبا بكم احبائي المستمعين في عالم القصص الراقيه', 'مرحباً بكم، أحبائي المستمعين، في عالم القصص الراقية.'), ('وخير ما نبدا به الصلاه والسلام على سيدنا وحبيبنا محمد صلى الله عليه وسلم', 'وخير ما نبدأ به الصلاة والسلام على سيدنا وحبيبنا محمد، صلى الله عليه وسلم.')]
model = None
active_model_path = None
_app_session_immediate_sync_count = 0
APP_SESSION_IMMEDIATE_SYNC_LIMIT = 2
_license_status_cache = {'valid': True, 'msg': 'Lisans durumu henüz doğrulanmadı.', 'checked_at': 0.0, 'inflight': False}
LICENSE_STATUS_TTL_SEC = 20.0
def _refresh_license_status_worker() -> Any:
    ...

def _ensure_license_check_async(force: bool) -> Any:
    ...

def _get_license_gate_status() -> Any:
    ...

def _get_today_utc_date_str() -> str:
    ...

def _get_today_request_count() -> int:
    ...

def _get_pending_log_count() -> int:
    ...

def _sync_logs_by_policy_worker() -> None:
    ...

def _sync_logs_by_policy_after_generation() -> None:
    ...

def log(msg: str) -> Any:
    ...

def _submit_to_main_thread(fn: Any) -> Any:
    ...

def _main_thread_worker() -> Any:
    ...

def _discover_model_paths(root: str) -> Any:
    ...

def _model_label(path: str) -> str:
    ...

def _load_model_on_main_thread(model_path: str) -> Any:
    ...

def _ensure_model_loaded(model_path: str | None) -> Any:
    ...

def load_selected_model_ui(model_path: str) -> Any:
    ...

def refresh_model_list_ui(current_path: str | None) -> Any:
    ...

def _as_mlx_audio(audio: Any) -> Any:
    ...

def _duration_seconds_mlx(audio: Any, sample_rate: int) -> float:
    ...

def _make_silence_mlx(sample_rate: int, seconds: float, dtype: Any) -> Any:
    ...

def _peak_mlx(audio: Any) -> Any:
    ...

def _safe_normalize_mlx(audio: Any, target_peak: float) -> Any:
    ...

def _peak_normalize_mlx(audio: Any, target_peak: float, max_gain: float) -> Any:
    ...

def _trim_edges_mlx(audio: Any, sample_rate: int, threshold: float, pad_ms: int) -> Any:
    ...

def _compress_long_silences_mlx(audio: Any, sample_rate: int, threshold: float, frame_ms: int, min_silence_ms: int, keep_ms: int) -> Any:
    ...

def _max_silence_run_seconds_mlx(audio: Any, sample_rate: int, threshold: float, frame_ms: int) -> float:
    ...

def _compress_abnormal_pauses_mlx(audio: Any, sample_rate: int, min_silence_ms: int, keep_ms: int) -> Any:
    ...

def _cleanup_short_arabic_pauses_mlx(audio: Any, sample_rate: int, chunk_text: str) -> Any:
    ...

def _normalize_text(text: str) -> str:
    ...

def _strip_transcript_timestamps(text: str) -> str:
    ...

def _normalize_arabic_text(text: str) -> str:
    ...

def _normalize_common_arabic_story_phrases(text: str) -> str:
    ...

def _split_arabic_story_paragraphs(text: str, max_paragraph_chars: int) -> Any:
    ...

def _inject_soft_arabic_story_punctuation(paragraph: str, soft_target: int) -> str:
    ...

def _prepare_arabic_text_for_chatterbox(text: str) -> str:
    ...

def _prepare_text_for_chatterbox(text: str, lang_code: str) -> str:
    ...

def _punc_norm_mlx_cuda_story(text: str, lang_code: str) -> str:
    ...

def _split_chunk_by_pause_markers(chunk_text: str) -> Any:
    ...

def _is_dialogue_line(line: str) -> bool:
    ...

def _is_emphasis_line(line: str) -> bool:
    ...

def _split_long_sentence(sentence: str, chunk_size: int, lang_code: str) -> Any:
    ...

def _sentence_split_keep_punct(line: str, lang_code: str) -> Any:
    ...

def _is_dialogue_block_text(text: str) -> bool:
    ...

def _pack_sentences_cuda_like(sentences: Any, chunk_size: int, min_chunk: int, allow_overflow: int) -> Any:
    ...

def _is_dialogue_block_text(text: str) -> bool:
    ...

def _should_keep_arabic_sentences_separate(sentences: Any, soft_size: int, is_dialogue_block: bool) -> bool:
    ...

def _pack_sentences_cuda_like(sentences: Any, chunk_size: int, min_chunk: int, allow_overflow: int, lang_code: str) -> Any:
    ...

def _build_cuda_like_story_blocks(text: str, lang_code: str) -> Any:
    ...

def _chunk_has_terminal_punct(text: str) -> bool:
    ...

def _split_text_story_mode(text: str, chunk_size: int, lang_code: str) -> Any:
    ...

def _split_text_pinokio_mode(text: str, chunk_size: int, lang_code: str) -> Any:
    ...

def _split_text_for_tts(text: str, chunk_size: int, mode: str, lang_code: str) -> Any:
    ...

def _estimate_chunk_duration_limit(chunk_text: str, lang_code: str) -> float:
    ...

def _dynamic_token_cap(chunk_text: str, user_max_tokens: int, lang_code: str) -> int | None:
    ...

def _arabic_sentence_level_regen_needed(chunk_text: str, audio: Any, sample_rate: int) -> bool:
    ...

def _regen_arabic_chunk_sentencewise(model: Any, chunk_text: str, ref_audio: Any, audio_prompt_sr: Any, exaggeration: float, cfg_weight: float, temperature: float, max_tokens: int, sample_rate: int, chunk_index: int, light_cleanup: bool) -> Any:
    ...

def _apply_language_profile(lang_code: str, has_reference_audio: bool, exaggeration: float, cfg_pace: float, temperature: float, chunk_size: int, chunk_gap_ms: int) -> Any:
    ...

def _generate_on_main_thread(model: Any, gen_kwargs: Any) -> Any:
    ...

def _generate_chunk_with_retry(model: Any, chunk_text: str, ref_audio: Any, audio_prompt_sr: Any, exaggeration: float, cfg_weight: float, temperature: float, max_tokens: int, sample_rate: int, chunk_index: int, safety_retry: bool, light_cleanup: bool, lang_code: str) -> Any:
    ...

def chunk_preview(metin: Any, chunk_size: Any, mode: Any, lang_choice: Any, referans_ses_yolu: Any) -> Any:
    ...

def hazirla_metin(metin: Any, lang_choice: Any) -> Any:
    ...

def hazirla_ve_onizle(metin: Any, chunk_size: Any, mode: Any, lang_choice: Any, referans_ses_yolu: Any) -> Any:
    ...

def add_pause_marker(metin: Any, marker: Any) -> Any:
    ...

def create_youtube_master_wav() -> Any:
    ...

def ses_uret(metin: Any, referans_ses_yolu: Any, lang_code: Any, selected_model_path: Any, exaggeration: Any, cfg_pace: Any, chunk_size: Any, temperature: Any, random_seed: Any, max_new_tokens: Any, chunk_gap_ms: Any, processing_mode: Any, safety_retry: Any, save_chunks: Any) -> Any:
    ...

def _safe_filename(name: str) -> str:
    ...

def _load_presets() -> dict:
    ...

def _save_presets(presets: dict) -> None:
    ...

def _preset_choices() -> Any:
    ...

def _copy_reference_audio_for_preset(preset_name: str, ref_path: str | None) -> str:
    ...

def save_current_preset(preset_name: Any, referans_ses_yolu: Any, lang_choice: Any, exaggeration: Any, cfg_pace: Any, chunk_size: Any, temperature: Any, random_seed: Any, max_new_tokens: Any, chunk_gap_ms: Any, processing_mode: Any, safety_retry: Any, save_chunks: Any) -> Any:
    ...

def load_selected_preset(preset_name: Any) -> Any:
    ...

def delete_selected_preset(preset_name: Any) -> Any:
    ...

custom_css = "\nbody { background-color: #0d0d0d !important; }\n.gradio-container {\n    background: linear-gradient(180deg, #1a1a1a 0%, #0d0d0d 100%) !important;\n    color: #e0e0e0 !important;\n    font-family: 'Inter', 'Segoe UI', sans-serif !important;\n    max-width: 1040px !important;\n    margin: 0 auto !important;\n}\nh1 {\n    background: linear-gradient(135deg, #ff4444 0%, #ff8800 100%);\n    -webkit-background-clip: text;\n    -webkit-text-fill-color: transparent;\n    font-weight: 800 !important;\n    text-align: center;\n    font-size: 1.6rem !important;\n}\nh3 { color: #ff6633 !important; font-size: 0.95rem !important; }\nbutton.primary {\n    background: linear-gradient(135deg, #cc2200 0%, #ff4400 100%) !important;\n    border: none !important;\n    border-radius: 10px !important;\n    color: white !important;\n    font-weight: 700 !important;\n    font-size: 1.05rem !important;\n    padding: 12px 0 !important;\n    box-shadow: 0 4px 20px rgba(255, 68, 0, 0.35) !important;\n    transition: all 0.2s ease !important;\n}\nbutton.primary:hover {\n    transform: translateY(-1px) !important;\n    box-shadow: 0 6px 25px rgba(255, 68, 0, 0.5) !important;\n}\n"
default_model_value = MODEL_PATH if MODEL_PATH in model_choices else model_choices[0] if model_choices else MODEL_PATH
def update_system_message() -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import re
import json
import shutil
import queue
import threading
import time
import datetime
import concurrent
import concurrent.futures
import concurrent.futures.Future
import license_manager
import gradio
import soundfile
import numpy
import mlx
import mlx.core
import mlx_audio
import mlx_audio.tts
import mlx_audio.tts.utils
import mlx_audio.tts.generate
import posixpath
import traceback