# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timedelta
from local_db import LocalDatabase
from pathlib import Path
from typing import Any, Dict, Optional, Tuple
from typing_extensions import Self
import hashlib
import json
import os
import requests
import subprocess
import threading
import time
import uuid

GIST_CONFIG = {'GIST_ID': '4499fc3b0d9fc69c94c027a32ec26a81', 'USERNAME': 'gundemsaniye-dot', 'ENCRYPTED_TOKEN': '2y0NZ1YMDj3fhboCSyd3GIaFrJ2JdTwZTUjs_phg'}
class LicenseManager:
    def __init__(self: Self) -> None: ...
    def _get_or_create_device_uuid(self: Self) -> str: ...
    def _get_auth_headers(self: Self) -> Dict[str, str]: ...
    def fetch_gist_data(self: Self) -> Optional[Dict[str, Any]]: ...
    def update_gist(self: Self, data: Dict[str, Any]) -> bool: ...
    def validate(self: Self) -> Tuple[bool, str, Optional[Dict[str, Any]]]: ...
    def check_daily_limit(self: Self) -> Tuple[bool, int]: ...
    def log_generation(self: Self, text: str, audio_duration: float, settings: Dict[str, Any]) -> Any: ...
    def sync_pending_logs(self: Self) -> Any: ...
    def start_background_sync(self: Self) -> Any: ...
    def _sync_loop(self: Self) -> Any: ...
    def stop_background_sync(self: Self) -> Any: ...
    def _get_mac_model(self: Self) -> str: ...
    def _get_macos_version(self: Self) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import requests
import json
import hashlib
import subprocess
import os
import time
import threading
import uuid
import datetime
import pathlib
import typing
import local_db